apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  namespace: student-management
spec:
  selector:
    app: student-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
  type: LoadBalancer